name: docs-check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'scripts/check_ascii.py'
      - '.gitattributes'

jobs:
  ascii_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: ASCII/UTF-8/LF check
        run: python scripts/check_ascii.py
